### ISSUE TITLE
`title` is not optional

### ISSUE THREAD

**Issue by lonix1** [Fooxly/vscode-provision-bar#7]
The [docs](https://github.com/Fooxly/vscode-provision-bar#%EF%B8%8F-available-settings) say this:
> title (optional): An object with the titles used for the amount of notes. * is the fallback text if the specific number is not listed. To show the amount use {0} inside the string.

It says "optional", but if I don't specify `title` then the extension ignores that keyword. (When I specify `title` it works.)

So either the docs are incorrect (it's not optional), or the behavior is incorrect.

**Comment by thom1606** [comment]
Hi there,
we have updated our package and fixed this issue. This is fixed from ProVision: Bar 4.0 and beyond.
